# Generated by Django 5.0 on 2024-12-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
