# Generated by Django 5.0 on 2024-12-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.FloatField(default=1000.0),
        ),
    ]
